zip/parcels.zip:
	mkdir -p zip
	curl -o zip/parcels.zip http://gis.phila.gov/gisdata/PARCELS_PWD.zip

zip/opa_2014.zip:
	mkdir -p zip
	http://www.phila.gov/OPA/Documents/TaxYear2014DataSet.zip

zip/opa_2015.zip:
	mkdir -p zip
	http://www.phila.gov/OPA/Documents/TaxYear2015DataSet.zip
